---
workflows:
  build_test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run something
      run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      save_cache:
        paths:
          - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
      run:
        name: run tests
        command: |
          . venv/bin/activate
          ./test.sh
      store_artifacts:
        path: test-reports
        destination: test-reports

  deploy:
    working_directory: ~/rep
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-deploy.txt
      - run:
          name: init .pypirc
          command: |
            echo "[pypi]" > ~/.pypirc
            echo "username = safuya" >> ~/.pypirc
            echo "password = ${PYPI_PASSWORD}" >> ~/.pypirc
      - run:
          name: make packages
          command: "python setup.py sdist bdist_wheel"
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*
