# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Managing the package

on: 
  push:
    #branches: '!master'
    jobs:
      - build_and_test
  create:
    tags: 
      - *
    task:
      - deploy

jobs:
  
  build_and_test:
    name: Build and Test the module
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Build dependancies
      run: pip install -r requirements.txt

    - name: Test with pytest
      run: pytest

    - name: Build the module
      run: python setup.py sdist

    - name: Install localy
      run: pip install -e .

  # Deploy it to PyPi
  deploy:
    name: Deploy to PyPi
    needs: build_and_test
    only: 
      - tags
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
